services:
    api:
      build: ./app
      deploy:
        replicas: 1 # Number of replicas for the API service, docker-compose up --scale api=3 or 2 or 1 to adjust the number of replicas

    nginx:
        image: nginx:1.27.4
        ports:
            - "5555:80"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        depends_on:
            - api

    grafana:
        image: grafana/grafana:11.5.2
        ports:
            - "8100:3000"
        volumes:
            - "grafana_config:/var/lib/grafana"

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.49.2
        links:
            - graphite-infra
        command: -storage_driver="statsd" -storage_driver_host="graphite-infra:8125" -storage_driver_db="cadvisor" --docker_only=true
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"

    graphite-business:
        image: graphiteapp/graphite-statsd:1.1.10-5
        ports:
            - "8090:80"
            - "8126:8126/udp"
        volumes:
            - ./statsd-business.config.json:/opt/statsd/config/udp.js

    graphite-infra:
        image: graphiteapp/graphite-statsd:1.1.10-5
        ports:
            - "8091:80"
            - "8125:8125/udp"
        volumes:
            - ./statsd-infra.config.json:/opt/statsd/config/udp.js


volumes:
    grafana_config:
        driver: local


    
